### ISSUE TITLE
patch_lib.py > IndexError: list index out of range

### ISSUE THREAD

**Issue by NikDzub** [Eltion/Tiktok-SSL-Pinning-Bypass#38]
---
name: Bug report
about: Bug report
title: "[BUG]"
labels: ''
assignees: Eltion

---

**Describe the bug**  
when running python3 patch_lib.py -i libsscronet.so -a arm64-v8a

Finding function offset in libsscronet_patched.so
Traceback (most recent call last):
  File "/Users/ihpt/Desktop/emu/tik-by/patch_lib.py", line 72, in <module>
  File "/Users/ihpt/Desktop/emu/tik-by/patch_lib.py", line 49, in patch_function
  File "/Users/ihpt/Desktop/emu/tik-by/patch_lib.py", line 21, in patch_function_arm64
IndexError: list index out of range

**Method**  
Patched APK

**App info**
 - Version: tiktok-v31.5.3
 - arm64-v8a

**Device info**
- Model: Google Nexus 4, Genymotion Emulator
- Android Version: 11

**Proxy tool**

**Logs**
Finding function offset in libsscronet_patched.so
Traceback (most recent call last):
  File "/Users/ihpt/Desktop/emu/tik-by/patch_lib.py", line 72, in <module>
  File "/Users/ihpt/Desktop/emu/tik-by/patch_lib.py", line 49, in patch_function
  File "/Users/ihpt/Desktop/emu/tik-by/patch_lib.py", line 21, in patch_function_arm64
IndexError: list index out of range

**Additional context**
Doesnt work w frida as well
the app is crashing and reopening
tried with the apk file provided + download from store

Thanks

**Comment by Cryxto** [comment]
well we got the same problem :(
